CREATE TABLE Students (
Student_id INTEGER NOT NULL AUTO_INCREMENT,
FN INTEGER NOT NULL,
Id_task INTEGER NOT NULL,
First_name VARCHAR(50) NOT NULL,
Last_name VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL, 
PRIMARY KEY (Student_id)
); 